class DummyData {

  DummyData._();

  static Map<String, dynamic> get tasker => {
    "id": 54458,
    "user_id": "20",
    "user_group_id": null,
    "identifier_id": null,
    "title": "Check In",
    "todo_date": "2025-06-26",
    "todo_time": "04:30:00",
    "location": null,
    "location_id": null,
    "fix_tasks": null,
    "maintenance_task_id": null,
    "mandatory": 0,
    "platform_check": 0,
    "platform": null,
    "todo_user_type": 0,
    "custom_link_id": null,
    "custom_link": null,
    "branch_id": 1,
    "group_id": null,
    "address": null,
    "vendor_id": null,
    "vendor_name": null,
    "priority": null,
    "reminder": null,
    "status": "In Progress",
    "recurring_id": null,
    "recurring": null,
    "reference_id": null,
    "reservation_name": null,
    "cohort_id": null,
    "cohort_name": null,
    "vin": null,
    "vehicle_name": null,
    "vehicle_image": null,
    "vehicle_status_id": null,
    "vehicle_status_category": null,
    "vehicle_status_checklist": null,
    "person": null,
    "person_id": null,
    "expense_attachment": null,
    "expense_amount": null,
    "expense_description": null,
    "category_id": null,
    "category_name": null,
    "subcategory_id": null,
    "subcategory_name": null,
    "expense_id": null,
    "expense_temp_id": null,
    "expense_to": null,
    "notes": null,
    "resolution_notes": null,
    "comments": null,
    "reason": null,
    "deleted_reason": null,
    "images": null,
    "mileage": null,
    "vehicle_group_id": null,
    "related_task_id": null,
    "time_change_reason": null,
    "clean_required": null,
    "odour": null,
    "complete_time_taken": null,
    "notes_complete": null,
    "complete_time_approved": 1,
    "further_task_id": null,
    "further_task_name": null,
    "deleted_at": null,
    "created_at": "2025-06-26T11:00:05.000000Z",
    "updated_at": "2025-06-26T11:00:05.000000Z",
    "completed_at": null,
    "trip_driven": null,
    "trip_review": null,
    "created_by": null,
    "updated_by": null,
    "deleted_by": null,
    "autotask": 0,
    "time_sensitive": 0,
    "platform_type": null,
    "rental_enquiry": null,
    "lead_id": null,
    "todo_date_changed": false,
    "parts": [],
    "supplies": [],
    "vinList": [],
    "userList": [
      {
        "id": 20,
        "hrm_id": 29,
        "first_name": "Imthiyaas",
        "last_name": "Ahamed",
        "phone": "9840498216",
        "email": "imthiyaas@support.com",
        "user_order": 11,
        "branch_id": 1,
        "from_time": "04:30:00",
        "to_time": "09:00:00",
        "from_time2": null,
        "to_time2": null,
        "unavailable_days": "Sunday",
        "shift_timings": null,
        "email_verified_at": null,
        "department": "7",
        "deleted_at": null,
        "created_at": "2024-06-26T21:18:49.000000Z",
        "updated_at": "2024-06-27T18:33:07.000000Z",
        "departments": {
          "id": 7,
          "name": "Support",
          "head": "1",
          "created_at": "2024-06-27T02:25:42.000000Z",
          "updated_at": "2024-06-27T02:25:42.000000Z"
        }
      }
    ],
    "display": {
      "task_title": "Check In",
      "task_time": "04:30:00",
      "completed_time": "00:15",
      "hasCompletedTime": false,
      "hasTimeSensitive": false,
      "hasDistance": false,
      "hasParts": false,
      "hasSupplies": false,
      "hasG": false,
      "hasVehicleHistory": false,
      "hasVendorInfo": false,
      "hasAttachments": false,
      "hasAddress": false,
      "hasCustomLink": false,
      "hasCompleted": false,
      "hasRelatedTask": false,
      "hasVehiclePlate": false,
      "hasReason": false,
      "hasReasonAttachments": false,
      "hasTimeChangeReason": false,
      "person_name": null,
      "vendor_location": null,
      "vins": [],
      "vehicle_image": null,
      "vehicle_plate": null,
      "vehicle_distance": null,
      "vehicle_name": null,
      "vehicle_or_person_name": null,
      "vendor": null,
      "addresses": null,
      "selectedAddress": null,
      "resources": [
        {
          "id": 20,
          "hrm_id": 29,
          "first_name": "Imthiyaas",
          "last_name": "Ahamed",
          "phone": "9840498216",
          "email": "imthiyaas@support.com",
          "user_order": 11,
          "branch_id": 1,
          "from_time": "04:30:00",
          "to_time": "09:00:00",
          "from_time2": null,
          "to_time2": null,
          "unavailable_days": "Sunday",
          "shift_timings": null,
          "email_verified_at": null,
          "department": "7",
          "deleted_at": null,
          "created_at": "2024-06-26T21:18:49.000000Z",
          "updated_at": "2024-06-27T18:33:07.000000Z",
          "departments": {
            "id": 7,
            "name": "Support",
            "head": "1",
            "created_at": "2024-06-27T02:25:42.000000Z",
            "updated_at": "2024-06-27T02:25:42.000000Z"
          }
        }
      ],
      "vehicles": null,
      "vehicleStatus": null,
      "vehicleStatusCategoryName": null,
      "vehicleHistoryIconColorCode": "",
      "relatedTaskName": null,
      "personId": null,
      "vehicleGroupId": null,
      "reason": null,
      "timeChangeReason": null,
      "notes": null,
      "customLinkText": null
    },
    "users": {
      "id": 20,
      "hrm_id": 29,
      "first_name": "Imthiyaas",
      "last_name": "Ahamed",
      "phone": "9840498216",
      "email": "imthiyaas@support.com",
      "user_order": 11,
      "branch_id": 1,
      "from_time": "04:30:00",
      "to_time": "09:00:00",
      "from_time2": null,
      "to_time2": null,
      "unavailable_days": "Sunday",
      "shift_timings": null,
      "email_verified_at": null,
      "department": "7",
      "deleted_at": null,
      "created_at": "2024-06-26T21:18:49.000000Z",
      "updated_at": "2024-06-27T18:33:07.000000Z",
      "departments": {
        "id": 7,
        "name": "Support",
        "head": "1",
        "created_at": "2024-06-27T02:25:42.000000Z",
        "updated_at": "2024-06-27T02:25:42.000000Z"
      }
    },
    "todoimages": [],
    "reason_images": [],
    "vehicles": []
  };

  static Map<String, dynamic> get vExpense => {
    "id": 7635,
    "expense_date": "2025-06-26",
    "approved": 1,
    "vehicle_id": 2019187,
    "vin": "5N1AT2MT4JC761637",
    "cohort_id": 1,
    "branch_code": 1,
    "subcategory_id": 65,
    "category_id": 21,
    "expense_amount": 347.8,
    "sales_tax": 29.8,
    "sales_tax_type": "%",
    "sales_tax_percentage": 10,
    "shipping_and_handling": 20,
    "expense_description": "test",
    "notes": null,
    "major_repair": null,
    "expense_to": 4,
    "parts_id": null,
    "checklist_id": null,
    "platform": "TaskerApp",
    "odometer": null,
    "payment_method_id": 2,
    "employee_id": 3,
    "deleted_at": null,
    "created_at": "2025-06-25T11:41:21.000000Z",
    "updated_at": "2025-06-27T14:18:11.000000Z",
    "vehicle": {
      "id": 9,
      "vehicle_id": 2019187,
      "vehicle_name": "2018 NISSAN ROGUE S SILVR",
      "vin": "5N1AT2MT4JC761637",
      "make": "NISSAN",
      "model": "ROGUE S SILVR",
      "year": "2018",
      "vehicle_number": "SZH 4207",
      "cohort_id": 1,
      "earnings": null,
      "utilization_rate": null,
      "vehicle_status": 3,
      "active": 1,
      "platform": null,
      "platform_from": null,
      "mileage": null,
      "wholesale_amount": null,
      "row_order": 2,
      "note": "Please ignore the last text, typed in error",
      "followup_date": "2025-04-28",
      "purchase_date": "2023-02-28",
      "purchase_price": 9300,
      "sold_date": null,
      "sold_price": null,
      "rental_status": 0,
      "title_registration": null,
      "vehicle_status_update": null,
      "is_vehicle": 1,
      "address": null,
      "bouncie": 1,
      "air_tag": 0,
      "permanent_plate": 1,
      "car_number": null,
      "oil_grade": null,
      "front_tire": null,
      "spare_tire": 1,
      "spare_key": 1,
      "registration_renewal_date": "2025-05-31",
      "rear_tire": null,
      "branch_code": 1,
      "toll_tags": 1,
      "toll_tags_id": "DFW. 04771056",
      "front_license_plate": 0,
      "tire_size": null,
      "insurance_agent": null,
      "insurance_cost": null,
      "current_odometer": null,
      "oil_change_odometer": null,
      "maintenance_check": null,
      "deleted_at": null,
      "created_at": "2023-02-28T15:02:04.000000Z",
      "updated_at": "2025-05-31T23:18:43.000000Z",
      "transaction_comments": null,
      "key_type": null
    },
    "expense_to_data": {
      "id": 4,
      "cohort_id": 1,
      "expense_to": "Cohort",
      "status": 1,
      "deleted_at": null,
      "created_at": "2023-07-31T04:57:02.000000Z",
      "updated_at": "2023-07-31T04:57:02.000000Z"
    },
    "cohort": {
      "id": 1,
      "cohort": "Fair Returns LP LLC",
      "fairpy_earnings": 30,
      "start_date": "2023-03-01",
      "end_date": null,
      "description": null,
      "earnings_payment_type": 1,
      "business_module": 1,
      "active": 1,
      "deleted_at": null,
      "created_at": "2022-12-31T00:32:34.000000Z",
      "updated_at": "2025-03-10T07:50:57.000000Z"
    },
    "category": {
      "id": 21,
      "name": "Post Purchase",
      "parent_id": null,
      "expense_to": null,
      "cohort_id": 1,
      "platform": "tasker-web",
      "is_generated": 0,
      "created_by": null,
      "updated_by": null,
      "deleted_at": null,
      "created_at": "2023-02-14T14:35:36.000000Z",
      "updated_at": "2024-01-08T20:59:06.000000Z"
    },
    "subcategory": {
      "id": 65,
      "name": "Transport",
      "parent_id": 21,
      "expense_to": 4,
      "cohort_id": 1,
      "platform": null,
      "is_generated": 0,
      "created_by": null,
      "updated_by": null,
      "deleted_at": null,
      "created_at": "2023-11-14T04:37:51.000000Z",
      "updated_at": "2024-07-09T03:33:59.000000Z"
    },
    "attachments": [
      {
        "id": 6501,
        "expense_id": 7635,
        "vin": "5N1AT2MT4JC761637",
        "name": "Screenshot_20250610_103931.png",
        "path": "expenses\/5N1AT2MT4JC761637\/685c0d78be9a3.png",
        "file_type": "png",
        "image_type": "original",
        "file_size": "237.45 KB",
        "deleted_at": null,
        "created_at": "2025-06-25T14:53:44.000000Z",
        "updated_at": "2025-06-25T14:53:44.000000Z"
      },
      {
        "id": 6503,
        "expense_id": 7635,
        "vin": "5N1AT2MT4JC761637",
        "name": "IMG_20250617_183831.jpg",
        "path": "expenses\/5N1AT2MT4JC761637\/685cdcf4c42bc.jpg",
        "file_type": "jpg",
        "image_type": "original",
        "file_size": "30.46 KB",
        "deleted_at": null,
        "created_at": "2025-06-26T05:39:00.000000Z",
        "updated_at": "2025-06-26T05:39:00.000000Z"
      },
      {
        "id": 6504,
        "expense_id": 7635,
        "vin": "5N1AT2MT4JC761637",
        "name": "invoice.pdf",
        "path": "expenses\/5N1AT2MT4JC761637\/685d1db5a6a6c.pdf",
        "file_type": "pdf",
        "image_type": "original",
        "file_size": "4.23 KB",
        "deleted_at": null,
        "created_at": "2025-06-26T10:15:17.000000Z",
        "updated_at": "2025-06-26T10:15:17.000000Z"
      }
    ],
    "payment_method": {
      "id": 2,
      "name": "Zelle",
      "status": 1,
      "platform": null,
      "deleted_at": null,
      "created_at": "2023-10-30T23:28:54.000000Z",
      "updated_at": "2023-10-30T23:28:54.000000Z"
    }
  };

}