class DummyData {

  DummyData._();

  static Map<String, dynamic> get tasker => {
    "id": 54458,
    "user_id": "20",
    "user_group_id": null,
    "identifier_id": null,
    "title": "Check In",
    "todo_date": "2025-06-26",
    "todo_time": "04:30:00",
    "location": null,
    "location_id": null,
    "fix_tasks": null,
    "maintenance_task_id": null,
    "mandatory": 0,
    "platform_check": 0,
    "platform": null,
    "todo_user_type": 0,
    "custom_link_id": null,
    "custom_link": null,
    "branch_id": 1,
    "group_id": null,
    "address": null,
    "vendor_id": null,
    "vendor_name": null,
    "priority": null,
    "reminder": null,
    "status": "In Progress",
    "recurring_id": null,
    "recurring": null,
    "reference_id": null,
    "reservation_name": null,
    "cohort_id": null,
    "cohort_name": null,
    "vin": null,
    "vehicle_name": null,
    "vehicle_image": null,
    "vehicle_status_id": null,
    "vehicle_status_category": null,
    "vehicle_status_checklist": null,
    "person": null,
    "person_id": null,
    "expense_attachment": null,
    "expense_amount": null,
    "expense_description": null,
    "category_id": null,
    "category_name": null,
    "subcategory_id": null,
    "subcategory_name": null,
    "expense_id": null,
    "expense_temp_id": null,
    "expense_to": null,
    "notes": null,
    "resolution_notes": null,
    "comments": null,
    "reason": null,
    "deleted_reason": null,
    "images": null,
    "mileage": null,
    "vehicle_group_id": null,
    "related_task_id": null,
    "time_change_reason": null,
    "clean_required": null,
    "odour": null,
    "complete_time_taken": null,
    "notes_complete": null,
    "complete_time_approved": 1,
    "further_task_id": null,
    "further_task_name": null,
    "deleted_at": null,
    "created_at": "2025-06-26T11:00:05.000000Z",
    "updated_at": "2025-06-26T11:00:05.000000Z",
    "completed_at": null,
    "trip_driven": null,
    "trip_review": null,
    "created_by": null,
    "updated_by": null,
    "deleted_by": null,
    "autotask": 0,
    "time_sensitive": 0,
    "platform_type": null,
    "rental_enquiry": null,
    "lead_id": null,
    "todo_date_changed": false,
    "parts": [],
    "supplies": [],
    "vinList": [],
    "userList": [
      {
        "id": 20,
        "hrm_id": 29,
        "first_name": "Imthiyaas",
        "last_name": "Ahamed",
        "phone": "9840498216",
        "email": "imthiyaas@support.com",
        "user_order": 11,
        "branch_id": 1,
        "from_time": "04:30:00",
        "to_time": "09:00:00",
        "from_time2": null,
        "to_time2": null,
        "unavailable_days": "Sunday",
        "shift_timings": null,
        "email_verified_at": null,
        "department": "7",
        "deleted_at": null,
        "created_at": "2024-06-26T21:18:49.000000Z",
        "updated_at": "2024-06-27T18:33:07.000000Z",
        "departments": {
          "id": 7,
          "name": "Support",
          "head": "1",
          "created_at": "2024-06-27T02:25:42.000000Z",
          "updated_at": "2024-06-27T02:25:42.000000Z"
        }
      }
    ],
    "display": {
      "task_title": "Check In",
      "task_time": "04:30:00",
      "completed_time": "00:15",
      "hasCompletedTime": false,
      "hasTimeSensitive": false,
      "hasDistance": false,
      "hasParts": false,
      "hasSupplies": false,
      "hasG": false,
      "hasVehicleHistory": false,
      "hasVendorInfo": false,
      "hasAttachments": false,
      "hasAddress": false,
      "hasCustomLink": false,
      "hasCompleted": false,
      "hasRelatedTask": false,
      "hasVehiclePlate": false,
      "hasReason": false,
      "hasReasonAttachments": false,
      "hasTimeChangeReason": false,
      "person_name": null,
      "vendor_location": null,
      "vins": [],
      "vehicle_image": null,
      "vehicle_plate": null,
      "vehicle_distance": null,
      "vehicle_name": null,
      "vehicle_or_person_name": null,
      "vendor": null,
      "addresses": null,
      "selectedAddress": null,
      "resources": [
        {
          "id": 20,
          "hrm_id": 29,
          "first_name": "Imthiyaas",
          "last_name": "Ahamed",
          "phone": "9840498216",
          "email": "imthiyaas@support.com",
          "user_order": 11,
          "branch_id": 1,
          "from_time": "04:30:00",
          "to_time": "09:00:00",
          "from_time2": null,
          "to_time2": null,
          "unavailable_days": "Sunday",
          "shift_timings": null,
          "email_verified_at": null,
          "department": "7",
          "deleted_at": null,
          "created_at": "2024-06-26T21:18:49.000000Z",
          "updated_at": "2024-06-27T18:33:07.000000Z",
          "departments": {
            "id": 7,
            "name": "Support",
            "head": "1",
            "created_at": "2024-06-27T02:25:42.000000Z",
            "updated_at": "2024-06-27T02:25:42.000000Z"
          }
        }
      ],
      "vehicles": null,
      "vehicleStatus": null,
      "vehicleStatusCategoryName": null,
      "vehicleHistoryIconColorCode": "",
      "relatedTaskName": null,
      "personId": null,
      "vehicleGroupId": null,
      "reason": null,
      "timeChangeReason": null,
      "notes": null,
      "customLinkText": null
    },
    "users": {
      "id": 20,
      "hrm_id": 29,
      "first_name": "Imthiyaas",
      "last_name": "Ahamed",
      "phone": "9840498216",
      "email": "imthiyaas@support.com",
      "user_order": 11,
      "branch_id": 1,
      "from_time": "04:30:00",
      "to_time": "09:00:00",
      "from_time2": null,
      "to_time2": null,
      "unavailable_days": "Sunday",
      "shift_timings": null,
      "email_verified_at": null,
      "department": "7",
      "deleted_at": null,
      "created_at": "2024-06-26T21:18:49.000000Z",
      "updated_at": "2024-06-27T18:33:07.000000Z",
      "departments": {
        "id": 7,
        "name": "Support",
        "head": "1",
        "created_at": "2024-06-27T02:25:42.000000Z",
        "updated_at": "2024-06-27T02:25:42.000000Z"
      }
    },
    "todoimages": [],
    "reason_images": [],
    "vehicles": []
  };

}